
DROP TABLE CMP_PRD   CASCADE CONSTRAINTS PURGE;
DROP TABLE ORD_DTL   CASCADE CONSTRAINTS PURGE;

DROP TABLE CAMPAIGN  CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCT   CASCADE CONSTRAINTS PURGE;
DROP TABLE ORDERS    CASCADE CONSTRAINTS PURGE;
DROP TABLE SHOP      CASCADE CONSTRAINTS PURGE;


DROP TABLE PERIOD    CASCADE CONSTRAINTS PURGE;
DROP TABLE SHP_STAT  CASCADE CONSTRAINTS PURGE;
DROP TABLE PAY_STAT  CASCADE CONSTRAINTS PURGE;
DROP TABLE PRD_TYPE  CASCADE CONSTRAINTS PURGE;
DROP TABLE CATEGORY  CASCADE CONSTRAINTS PURGE;
DROP TABLE APP_USER  CASCADE CONSTRAINTS PURGE;
DROP TABLE USR_TYPE  CASCADE CONSTRAINTS PURGE;

BEGIN
  FOR t IN (
    -- FACT
    SELECT 'DW_FACT_ORDER_LINE' AS table_name FROM dual UNION ALL
    SELECT 'DW_FACT_ORDER'      FROM dual UNION ALL

    -- BRIDGE
    SELECT 'DW_BRIDGE_CAMPAIGN_PRODUCT' FROM dual UNION ALL

    -- DIM
    SELECT 'DW_DIM_CAMPAIGN'    FROM dual UNION ALL
    SELECT 'DW_DIM_PRODUCT'     FROM dual UNION ALL
    SELECT 'DW_DIM_SHOP'        FROM dual UNION ALL
    SELECT 'DW_DIM_SHP_STAT'    FROM dual UNION ALL
    SELECT 'DW_DIM_PAY_STAT'    FROM dual UNION ALL
    SELECT 'DW_DIM_PRD_TYPE'    FROM dual UNION ALL
    SELECT 'DW_DIM_CATEGORY'    FROM dual UNION ALL

    -- STAGING
    SELECT 'STG_CMP_PRD'        FROM dual UNION ALL
    SELECT 'STG_CAMPAIGN'       FROM dual UNION ALL
    SELECT 'STG_ORD_DTL'        FROM dual UNION ALL
    SELECT 'STG_ORDERS'         FROM dual UNION ALL
    SELECT 'STG_PRODUCT'        FROM dual UNION ALL
    SELECT 'STG_SHOP'           FROM dual
  )
  LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF; -- -942 = table or view does not exist
    END;
  END LOOP;
END;

